---
name: bookmark

services:
  ui:
    container_name: bookmark
    image: node:lts-alpine3.23@sha256:2bdb65ed1dab192432bc31c95f94155ca5ad7fc1392fb7eb7526ab682fa5bf14
    working_dir: /app
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tty: true
    environment:
      CONFIG_FILE: /app/config/config.yaml
    ports:
      - "5173:5173"

  httpd:
    container_name: httpd
    image: httpd
    ports:
      - "8000:80"
    profiles: ["docker-labels"]
    labels:
      - "bookmark.enabled=true"
      - "bookmark.app.id=httpd"
      - "bookmark.app.icon=apache"
      - "bookmark.app.name=Httpd"
      - "bookmark.app.url=http://localhost:8000"
      - "bookmark.app.roles=bookmark_admin"
      - "bookmark.app.group=admin"
