---
name: bookmark

services:
  ui:
    container_name: bookmark
    # node:lts-alpine3.23
    image: node@sha256:d1b3b4da11eefd5941e7f0b9cf17783fc99d9c6fc34884a665f40a06dbdfc94f
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    environment:
      CONFIG_FILE: /app/config/config.yaml
    ports:
      - '5173:5173'
